// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiQBkPs2qoLMPjBndvhD5cXIcd7GAcB88',
    appId: '1:218382921931:web:b34d6046679478cb5b2b4e',
    messagingSenderId: '218382921931',
    projectId: 'weatherapp-44332',
    authDomain: 'weatherapp-44332.firebaseapp.com',
    storageBucket: 'weatherapp-44332.appspot.com',
    measurementId: 'G-2MBV99GZHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUNFCwTnXCpUjp-GBEnsczODFgpZK9cqA',
    appId: '1:218382921931:android:717281114db14c1b5b2b4e',
    messagingSenderId: '218382921931',
    projectId: 'weatherapp-44332',
    storageBucket: 'weatherapp-44332.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnTzftHTm057Lqe-7Txw2vMnjAcDs9SUQ',
    appId: '1:218382921931:ios:9a4eb1867e8765ef5b2b4e',
    messagingSenderId: '218382921931',
    projectId: 'weatherapp-44332',
    storageBucket: 'weatherapp-44332.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiQBkPs2qoLMPjBndvhD5cXIcd7GAcB88',
    appId: '1:218382921931:web:4db492249136a26f5b2b4e',
    messagingSenderId: '218382921931',
    projectId: 'weatherapp-44332',
    authDomain: 'weatherapp-44332.firebaseapp.com',
    storageBucket: 'weatherapp-44332.appspot.com',
    measurementId: 'G-ZR0JRLTW0T',
  );
}
